
log = reports/job_$(Cluster).log
error = reports/job_$(Cluster)_$(Process).err
output = reports/job_$(Cluster)_$(Process).out

requirements = (Target.HasCHTCStaging == true)
container_image = file:///staging/nwcollier/h2py-container.sif

executable = fit_model.sh      

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

arguments = $(Process)

transfer_input_files = fit_model_remote.py, MSL_GBR_Vindija_model3.yaml, options_MSL_GBR_Vindija3.yaml, data_MSL_GBR_Vindija

request_cpus = 1
request_memory = 2GB
request_disk = 1GB

queue 30
